### ISSUE TITLE
libusb and libgtk for Ubuntu 14.04

### ISSUE THREAD

**Issue by btegs** [pjanouch/sensei-raw-ctl#7]
When building on Ubuntu 14.04, I had to make sure to have libusb-1.0-0-dev and libgtk-3-dev installed in order to build from source without errors. When re-running the cmake command with those two packages installed, this is my output:

-- The C compiler identification is GNU 4.8.2
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.26") 
-- checking for module 'libusb-1.0'
--   found libusb-1.0, version 1.0.17
-- checking for module 'gtk+-3.0'
--   found gtk+-3.0, version 3.10.8
-- Configuring done
-- Generating done
-- Build files have been written to: /home/brian/sensei-raw-ctl/build

If you you try to build it on Ubuntu and if it works without issues with those two packages installed via apt or aptitude, then update the README. Thanks!

**Comment by pjanouch** [comment]
Eeeeh, sort of invalid. I don't want to put any distribution-specific package information in the README. I wouldn't mind if someone made a pull request with Debian packaging files, though. The best thing, of course, would be to patch the few major issues with this application (handle USB errors a bit better and rearrange the GUI to make more sense) and get it included in Debian.

However it's a very low priority task for me.
